services:
        my.handler.session_idle:
                class: AdminBundle\Services\SessionIdleHandler
                arguments: ["@session", "@security.context", "@router", %session_max_idle_time%]
                tags:
                    - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }
#    admin.example:
#        class: AdminBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
