detalle_index:
    path:     /list/{remember}
    defaults: { _controller: "NomencladorBundle:NomDetalle:index",remember:null }
    methods:  GET
detalle_listar:
    path:      /listar/
    defaults: { _controller: "NomencladorBundle:NomDetalle:listar" }
    methods:  [GET, POST]
detalle_show:
    path:     /{id}/show
    defaults: { _controller: "NomencladorBundle:NomDetalle:show" }
    methods:  GET

detalle_new:
    path:     /new
    defaults: { _controller: "NomencladorBundle:NomDetalle:new" }
    methods:  [GET, POST]

detalle_insert:
    path:     /insert/
    defaults: { _controller: "NomencladorBundle:NomDetalle:insert" }
    methods:  [GET, POST]

detalle_edit:
    path:     /{id}/edit
    defaults: { _controller: "NomencladorBundle:NomDetalle:edit" }
    methods:  [GET, POST]
detalle_exportar:
    path:      /exportar/
    defaults: { _controller: "NomencladorBundle:NomDetalle:exportar" }
    methods:  [GET, POST]
detalle_delete:
    path:     /{id}/delete
    defaults: { _controller: "NomencladorBundle:NomDetalle:delete" }
    methods:  DELETE

detalle_eliminar:
    path:      /eliminar/
    defaults: { _controller: "NomencladorBundle:NomDetalle:eliminar" }
    methods:  [GET, POST]
    
detalle_deleteAll:
    path:      /detalle_deleteAll/
    defaults: { _controller: "NomencladorBundle:NomDetalle:deleteSelect" }
    methods:  [GET, POST]

detalle_activar:
    path:      /activar/
    defaults: { _controller: "NomencladorBundle:NomDetalle:SetActivo" }
    methods:  [GET, POST]