security:
    encoders:
        AdminBundle\Entity\Usuario: sha512

    providers:
        main:
            entity:
                class: AdminBundle\Entity\Usuario
                property: usuario

    firewalls:
        secured_area:
            pattern:    ^/
            anonymous: ~
            form_login:
                login_path: /login
                check_path: /login_check
                default_target_path: /
                always_use_default_target_path: true
            logout:
                path: /logout
                target: /login
                handlers: [loggout_listener]

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: '%http_protocol%' }
        - { path: ^/*, roles: IS_AUTHENTICATED_FULLY , requires_channel: '%http_protocol%'}
