<?php

namespace AdminBundle\Repository;
use Doctrine\ORM\EntityRepository;

/**
 * RolRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RolRepository extends EntityRepository
{
    public function findRolPermiso($idRol, $idPermiso){

        $q = $this->createQueryBuilder('a')
            ->select('a')
            ->innerJoin('a.permisos', 'p')
            ->where('a.idRol = :idRol')
            ->andWhere('p.idPermiso = :idPermiso')
            ->setParameter('idRol', $idRol)
            ->setParameter('idPermiso', $idPermiso)
        ;

        return $q->getQuery()->getArrayResult();
    }
}
