<?php

namespace AdminBundle\Repository;

/**
 * TrazaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TrazaRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllOrderedByFecha() {
        $em = $this->getEntityManager();
        $dql = 'SELECT traz
            FROM AdminBundle:Traza traz ORDER BY traz.fechaCreacion DESC';
        $consulta = $em->createQuery($dql);
        $result = $consulta->getResult();
        return $result;
    }
}
