<?php

namespace NomencladorBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * DatNormaAseguramientoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DatNormaAseguramientoRepository extends EntityRepository
{
}
