<?php

namespace NomencladorBundle\Repository;

use Doctrine\ORM\EntityRepository;
use NomencladorBundle\Util\Util;

/**
 * NomMedidorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NomMedidorRepository extends EntityRepository
{
    public function listarDelExportarMedidor($filtroNombre)
    {
        $em = $this->getEntityManager();
        $datas = Util::whereFiltrar($em, 'NomencladorBundle:NomMedidor',"", $filtroNombre,"","","","","",
                                   "","","","","",false);
        $data = [];
        foreach ($datas as $n) {
            $data[] = array(
                'nombre' => $n->getNombre(),
                'activo' => $n->getActivo() == true ? 'Si' : 'No');
        }

        return $data;
    }
}
