<?php

namespace ParteDiarioBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DatPlanRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DatPlanRepository extends EntityRepository
{
    public function deleteAll($entidad, $campo_id, $array_ids)
    {
        $em = $this->getEntityManager();
        $consulta = $em->createQuery('DELETE  FROM ' . $entidad . ' cp   WHERE cp.' . $campo_id . ' IN  ( ' . $array_ids . ')');
        $consulta->execute();
        return $consulta;
    }


    public function existenciaPlanProduccion($tipoplan, $ejercicio, $ueb, $producto, $um, $md)
    {
        $where = '1=1';
        if ($tipoplan != '') {
            $where .= ' AND cp.idtipoplan  =' . $tipoplan;
        }
        if ($ejercicio != '') {
            $where .= ' AND cp.idejercicio =' . $ejercicio;
        }
        if ($ueb != '') {
            $where .= ' AND cp.idueb =' . $ueb;
        }
        if ($producto != '') {
            $where .= ' AND cp.idproducto =' . $producto;
        }
        if ($um != '') {
            $where .= ' AND cp.idunidadmedida =' . $um;
        }
        if ($md != '') {
            $where .= ' AND cp.idmonedadestino =' . $md;
        }

        $em = $this->getEntityManager();
        $consulta = $em->createQuery('select cp
                                         from ParteDiarioBundle:DatPlanProduccion cp
                                          where ' . $where);
        $result['count'] = count($consulta->getResult());
        $result['datos'] = $consulta->getResult();
        return $result;

    }

    public function existenciaPlanVentas($tipoplan, $ejercicio, $ueb, $producto, $um, $md, $cliente, $tipo, $entidad)
    {
        $where = '1=1';
        if ($tipoplan != 0 && $tipoplan != '') {
            $where .= ' AND cp.idtipoplan  =' . $tipoplan;
        }
        if ($ejercicio != 0 && $ejercicio != '') {
            $where .= ' AND cp.idejercicio =' . $ejercicio;
        }
        if ($ueb != 0 && $ueb != '') {
            $where .= ' AND cp.idueb =' . $ueb;
        }
        if ($producto != 0 && $producto != '') {
            $where .= ' AND cp.idproducto =' . $producto;
        }
        if ($um != 0 && $um != '') {
            $where .= ' AND cp.idunidadmedida =' . $um;
        }
        if ($md != 0 && $md != '') {
            $where .= ' AND cp.idmonedadestino =' . $md;
        }
        if ($cliente != 0 && $cliente != '') {
            $where .= ' AND cp.idgrupocliente =' . $cliente;
        }
        if ($tipo != null && $tipo != 0 && $tipo != '') {
            $where .= ' AND cp.is_val =' . $tipo;
        }
        if ($entidad != null && $entidad != 0 && $entidad != '') {
            $where .= ' AND cp.identidad =' . $entidad;
        }

        $em = $this->getEntityManager();
        $consulta = $em->createQuery('select cp
                                         from ParteDiarioBundle:DatPlanVenta cp
                                          where ' . $where);
        $result['count'] = count($consulta->getResult());
        $result['datos'] = $consulta->getResult();

        return $result;

    }

    public function existenciaPlanAseguramiento($tipoplan, $ejercicio, $ueb, $idaseguramiento, $um, $md)
    {
        $where = '1=1';
        if ($tipoplan != 0 && $tipoplan != '') {
            $where .= ' AND cp.idtipoplan  =' . $tipoplan;
        }
        if ($ejercicio != 0 && $ejercicio != '') {
            $where .= ' AND cp.idejercicio =' . $ejercicio;
        }
        if ($ueb != 0 && $ueb != '') {
            $where .= ' AND cp.idueb =' . $ueb;
        }
        if ($idaseguramiento != 0 && $idaseguramiento != '') {
            $where .= ' AND cp.idaseguramiento =' . $idaseguramiento;
        }
        if ($um != 0 && $um != '') {
            $where .= ' AND cp.idunidadmedida =' . $um;
        }
        if ($md != 0 && $md != '') {
            $where .= ' AND cp.idmonedadestino =' . $md;
        }

        $em = $this->getEntityManager();
        $consulta = $em->createQuery('select cp
                                         from ParteDiarioBundle:DatPlanAseguramiento cp
                                          where ' . $where);
        $result['count'] = count($consulta->getResult());
        $result['datos'] = $consulta->getResult();

        return $result;

    }

    public function existenciaPlanPortador($tipoplan, $ejercicio, $ueb, $port, $um, $md)
    {
        $where = '1=1';
        if ($tipoplan != 0 && $tipoplan != '') {
            $where .= ' AND cp.idtipoplan  =' . $tipoplan;
        }
        if ($ejercicio != 0 && $ejercicio != '') {
            $where .= ' AND cp.idejercicio =' . $ejercicio;
        }
        if ($ueb != 0 && $ueb != '') {
            $where .= ' AND cp.idueb =' . $ueb;
        }
        if ($port != 0 && $port != '') {
            $where .= ' AND cp.idportador =' . $port;
        }
        if ($um != 0 && $um != '') {
            $where .= ' AND cp.idunidadmedida =' . $um;
        }
        if ($md != 0 && $md != '') {
            $where .= ' AND cp.idmonedadestino =' . $md;
        }

        $em = $this->getEntityManager();
        $consulta = $em->createQuery('select cp
                                         from ParteDiarioBundle:DatPlanPortador cp
                                          where ' . $where);
        $result['count'] = count($consulta->getResult());
        $result['datos'] = $consulta->getResult();

        return $result;

    }



    public function existenciaPlanAcopioDestino($tipoplan, $ejercicio, $ueb, $producto, $ent, $um, $md)
    {
        $where = '1=1';
        if ($tipoplan != 0 && $tipoplan != '') {
            $where .= ' AND cp.idtipoplan  =' . $tipoplan;
        }
        if ($ejercicio != 0 && $ejercicio != '') {
            $where .= ' AND cp.idejercicio =' . $ejercicio;
        }
        if ($ueb != 0 && $ueb != '') {
            $where .= ' AND cp.idueb =' . $ueb;
        }
        if ($producto != 0 && $producto != '') {
            $where .= ' AND cp.idproducto =' . $producto;
        }
        if ($um != 0 && $um != '') {
            $where .= ' AND cp.idunidadmedida =' . $um;
        }
        if ($md != 0 && $md != '') {
            $where .= ' AND cp.idmonedadestino =' . $md;
        }
        if ($ent != 0 && $ent != '') {
            $where .= ' AND cp.identidad =' . $md;
        }

        $em = $this->getEntityManager();
        $consulta = $em->createQuery('select cp
                                         from ParteDiarioBundle:DatPlanAcopioDestino cp
                                          where ' . $where);
        $result['count'] = count($consulta->getResult());
        $result['datos'] = $consulta->getResult();

        return $result;

    }


}
