<?php

namespace ReporteBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * DatIndicadoresRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DatIndicadoresRepository extends EntityRepository
{
}
