<?php

namespace ReporteBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * DatListasDatosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DatListasDatosRepository extends EntityRepository
{
}
