<?php

namespace ReporteBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * DatPeriodosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DatPeriodosRepository extends EntityRepository
{
}
