<?php

namespace ReporteBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * DatReportesFilasResumenRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DatReportesFilasResumenRepository extends EntityRepository
{
}
