<?php

namespace ReporteBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * NomTiposDatosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NomTiposDatosRepository extends EntityRepository
{
}
