<?php

namespace ParteDiarioBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * DatPartePortadorMedidorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DatPartePortadorMedidorRepository extends EntityRepository
{
}
