<?php

namespace ParteDiarioBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * DatParteDiarioConsumoMateriaPrimaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DatParteDiarioConsumoMateriaPrimaRepository extends EntityRepository
{

}
